previewsEnabled: true
services:
- type: web
  name: monorepo-test-service
  branch: main
  env: node
  buildCommand: cd service && ./build.sh
  startCommand: cd service && ./start.sh
  buildFilter:
    paths:
    - service/**
  numInstances: 2
  envVars:
    - key: example_secret
      sync: false
- type: web
  name: monorepo-test-service-docker
  branch: main
  env: docker
  dockerfilePath: ./service-docker/Dockerfile
  dockerContext: ./service-docker/
  dockerCommand: bash ./start.sh
  healthCheckPath: /health-check
  buildFilter:
    paths:
    - service-docker/**
  scaling:
    minInstances: 1         # Required
    maxInstances: 3         # Required
    targetMemoryPercent: 60 # Optional if targetCPUPercent is set (valid: 1-90)
    targetCPUPercent: 60    # Optional if targetMemory is set (valid: 1-90)
- type: web
  name: monorepo-test-static-site
  branch: main
  env: static
  buildCommand: cd static-site && ./build.sh
  staticPublishPath: ./static-site/
  buildFilter:
    paths:
    - static-site/**
    ignoredPaths:
    - "**/*.md"
- type: cron
  name: monorepo-test-cron-job
  env: go
  buildCommand: cd cron-job && ./build.sh
  startCommand: cd cron-job && ./start.sh
  schedule: "0 5 * * *"
  buildFilter:
    paths:
    - cron-job/**
- type: cron
  name: monorepo-test-cron-job-docker
  env: docker
  dockerfilePath: ./cron-job-docker/Dockerfile
  dockerContext: ./cron-job-docker/
  dockerCommand: bash ./start.sh
  schedule: "0 5 * * *"
  buildFilter:
    paths:
    - cron-job-docker/**
# A Redis instance 
- type: redis
  name: monorepo-test-redis
  ipAllowList: [] # Only allow internal connections
databases:
  # A Pro database instance with a read replica
  - name: monorepo-test-postgresql # Required
    ipAllowList: [] # Only allow internal connections
    plan: pro # Default: starter
    readReplicas: # Default: does not add a read replica
      - name: monorepo-test-postgresql-replica

  # A Pro database that enables high availability
  - name: monorepo-test-postgresql-highly-available
    ipAllowList: [] # Only allow internal connections
    plan: pro
    highAvailability:
      enabled: true
