previewsEnabled: false
services:
- type: web
  name: monorepo-test-static-site
  branch: main
  env: static
  buildCommand: cd static-site && ./build.sh
  staticPublishPath: ./static-site/
  buildFilter:
    paths:
    - static-site/**
    ignoredPaths:
    - "**/*.md"
